server.port: 8080
spring:
  minio:
    url: http://localhost:9000
    bucket: storage
    access-key: miniorupesh
    secret-key: minorupesh


  data:
    mongodb:
      uri: mongodb://adminUser:adminPassword@localhost/content_db?authSource=admin
      database: content_db
      auto-index-creation: false





javers:
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000
  snapshotCollectionName: "Audit_table"
  headCollectionName: "Audit_id"
  schemaManagementEnabled: true







