server.port: 8080
spring:
  minio:
    url: http://localhost:9000
    bucket: storage
    access-key: miniorupesh
    secret-key: minorupesh


  data:
    mongodb:
     database: content_db
     port: 27017




javers:
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000
  snapshotCollectionName: "Audit_table"
  headCollectionName: "Audit_id"
  schemaManagementEnabled: true







